default: cmult

# target: prerequisites/dependencies
cmult: cmult.c complex.c
	# commands to be executed sequentially in order to compile the target
	# note: must be indented
		cc -o cmult cmult.c complex.c
