<div class="mermaid">
    graph TD
        subgraph L
            p1
            k1
            p
            k
            p3
        end
        subgraph R
            p2
            k2
            e1[null]
            e2[null]   
            p4
        end
        p3 --> p2
</div>

